name: Backend CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
    paths:
      - 'apps/backend/**'

jobs:
  check-version:
    name: Comprueba bump de versión
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de main (base de la PR)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: main-base

      - name: Obtener versión en main
        id: mainpkg
        run: |
          cd main-base/apps/backend
          echo "VERSION_MAIN=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Checkout de la PR (head)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: pr-head

      - name: Obtener versión en PR
        id: prpkg
        run: |
          cd pr-head/apps/backend
          echo "VERSION_PR=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Comparar versiones
        run: |
          if [ "${{ steps.prpkg.outputs.VERSION_PR }}" = "${{ steps.mainpkg.outputs.VERSION_MAIN }}" ]; then
            echo "::error ::No has incrementado la versión en package.json"
            exit 1
          fi

  build-and-push:
    name: Build & Push Docker (sólo tras merge)
    needs: check-version
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Obtener versión final
        id: pkg
        run: |
          cd apps/backend
          echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_OUTPUT
      - name: Log in a GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build de la imagen
        run: |
          cd apps/backend
          docker build -t ghcr.io/${{ github.repository_owner }}/backend-app:${{ steps.pkg.outputs.VERSION }} .
          docker tag ghcr.io/${{ github.repository_owner }}/backend-app:${{ steps.pkg.outputs.VERSION }} ghcr.io/${{ github.repository_owner }}/backend-app:latest
      - name: Push de las imágenes
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/backend-app:${{ steps.pkg.outputs.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/backend-app:latest
