name: Build & Push Backend Docker

on:
  push:
    branches:
      - main
    paths:
      - 'apps/backend/**'

jobs:
  build-and-push:
    name: 🚀 Build & Push Docker
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Get version from package.json
        id: pkg
        run: |
          cd apps/backend
          echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          cd apps/backend
          docker build -t ghcr.io/${{ github.repository_owner }}/backend-app:${{ steps.pkg.outputs.VERSION }} .
          docker tag ghcr.io/${{ github.repository_owner }}/backend-app:${{ steps.pkg.outputs.VERSION }} ghcr.io/${{ github.repository_owner }}/backend-app:latest

      - name: Push Docker images
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/backend-app:${{ steps.pkg.outputs.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/backend-app:latest
