name: Build and Push Backend Docker Image

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'apps/backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Get version from package.json (current branch)
        id: pkg
        run: |
          cd apps/backend
          echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Get version from package.json (main branch)
        id: mainpkg
        run: |
          git fetch origin main
          VERSION_MAIN=$(git show origin/main:apps/backend/package.json | jq -r .version)
          echo "VERSION_MAIN=$VERSION_MAIN" >> $GITHUB_OUTPUT

      - name: Check if version has changed
        run: |
          if [ "${{ steps.pkg.outputs.VERSION }}" = "${{ steps.mainpkg.outputs.VERSION_MAIN }}" ]; then
            echo "La versión no ha cambiado. Debes actualizar la versión en package.json."
            exit 1
          fi

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          cd apps/backend
          docker build -t ghcr.io/${{ github.repository_owner }}/backend-app:${{ steps.pkg.outputs.VERSION }} .
          docker tag ghcr.io/${{ github.repository_owner }}/backend-app:${{ steps.pkg.outputs.VERSION }} ghcr.io/${{ github.repository_owner }}/backend-app:latest

      - name: Push Docker images
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/backend-app:${{ steps.pkg.outputs.VERSION }}
          docker push ghcr.io/${{ github.repository_owner }}/backend-app:latest